---
- hosts: "{{ targets }}"
  become: true
  become_user: root
  tasks:
    - debug:
        msg: "{{ ansible_hostname }}:nodes"
      when: "targets == 'nodes' or 'nodes' in group_names"


    - debug:
        msg: "{{ ansible_hostname }}:nas"
      when: "targets == 'nas' or 'nas' in group_names"
