session_name: 4k
global_options:
  pane-active-border-style: "fg=red"
  window-status-current-style: "bg=red"
windows:
- focus: 'true'
  layout: 4472,172x84,0,0[172x8,0,0,0,172x15,0,9,1,172x59,0,25{74x59,0,25[74x29,0,25,2,74x29,0,55,5],97x59,75,25,4}]
  options: {}
  panes:
  - htop
  - watch docker ps -a
  - focus: 'true'
    shell_command: ''
  - ''
  - ''
  start_directory: "${PWD}"
  window_name: bash
