apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
subsets:
- addresses:
  - ip: 192.168.0.251
  ports:
  - port: 1990
    protocol: TCP
- addresses:
  - ip: 192.168.0.252
  ports:
  - port: 1990
    protocol: TCP
- addresses:
  - ip: 192.168.0.253
  ports:
  - port: 1990
    protocol: TCP

