apiVersion: v1
kind: Pod
metadata:
  name: nginx-0
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
    - name: test-volume
      mountPath: /mnt
  volumes:
  - name: test-volume
    glusterfs:
      endpoints: glusterfs-cluster
      path: '/gv0'
